### PR TITLE
Conditional import

### PR DESCRIPTION
**Pull request by bijoshtj**
eg: 
import com.abc.x|com.bcd.x|com.def.x asx

During compile time, it will modify statement to any one from the package list [com.abc. com.bcd, com,def], based on the availablity.

### CODE REVIEW

**Comment by Bijoshtj** [comment]
closing because of wrong target branch

**Comment by souparno** [comment]
Hi BIjosh,
 I think the multiple package import is allready present https://github.com/gameclosure/js.io/blob/master/packages/jsio.js#L979
the syntax is : from abc,def,ghi ....

**Comment by Bijoshtj** [comment]
@souparno 
the line u pointed is for solving 'import abc.xyz as xyz, ced.xyz as xyz2' ie, for multiple import in same line. there is also option like 'from abc.module import abc'

What im trying to achieve is suppose i do 'import abc.x|com.x as x', if its present in module abc, it will serve from abc else from com automatically.

**Comment by souparno** [comment]
ok, i understand :+1:

**Pull request closed without merging**
